### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by eszlari** [derat/xsettingsd#21]
Now with a complete cmake build system merged (and a systemd unit added), I think it would make sense to tag a new release.

**Comment by eszlari** [comment]
Maybe as last change before the (final) release, the C++ standard should be set (98 or 11?).

**Comment by derat** [comment]
I don't object to setting the C++ standard. It looks like `-std=c++98` and `-std=c++11` both work. I'd probably use some 11 features if I were changing the code now, but I doubt I'll be changing it anytime soon.

I'd prefer to avoid tagging a new release until there are changes to the packaged code, as it feels like unnecessary churn for packagers and users otherwise. Please let me know if there are benefits to tagging a new release that I'm not thinking of, though!

**Comment by eszlari** [comment]
> I don't object to setting the C++ standard. It looks like `-std=c++98` and `-std=c++11` both work. I'd probably use some 11 features if I were changing the code now, but I doubt I'll be changing it anytime soon.

I tested it: xsettingsd itself can be compiled with `-std=c++98`, while the tests requires `-std=c++11`. I guess not setting it explicitly and thus using the default compiler setting is more future proof for googletest.

> I'd prefer to avoid tagging a new release until there are changes to the packaged code, as it feels like unnecessary churn for packagers and users otherwise. Please let me know if there are benefits to tagging a new release that I'm not thinking of, though!

systemd unit file?

**Comment by derat** [comment]
> > I'd prefer to avoid tagging a new release until there are changes to the packaged code, as it feels like unnecessary churn for packagers and users otherwise. Please let me know if there are benefits to tagging a new release that I'm not thinking of, though!
> 
> systemd unit file?

I think that any distro that's packaged xsettingsd has already made a decision about how (or if) it should be started automatically, though, and the same goes for anyone who has built it from source on their local system. The systemd config is useful for new users who want to start the service via systemd (instead of e.g. `.xsessionrc` or `.xinitrc`), but I don't see how having a new release would affect them.

**Comment by eszlari** [comment]
> The systemd config is useful for new users who want to start the service via systemd (instead of e.g. `.xsessionrc` or `.xinitrc`), but I don't see how having a new release would affect them.

They would first have to download that file from the git repo, copy it to `/etc/systemd/user` or `~/.config/systemd/user` and adjust the file for the path to the binary. If it comes pre-packaged with their distribution, they only need to run

```
$ systemctl --user enable xsettingsd
```
and be done with it.

But also the cmake build system is useful to packagers: suppose you want create a new distribution. CMake will be needed anyway, because many important projects require it (LLVM, KDE etc.). But Scons is relatively obscure nowadays, and you could spare packagers from having to build it only for a few packages.

**Comment by derat** [comment]
Thanks for elaborating!

@xtaran, sorry to bug you again, but do you have opinions about this? Ideally I'd be able to tag a new release as being recommended for new users while telling maintainers that they don't need to bother updating the package. Is there some way (in the Debian world) for upstream to communicate this?

**Comment by xtaran** [comment]
> @xtaran, sorry to bug you again, but do you have opinions about this?

About what? Shipping a systemd service file? C++ syntax generations?

> Ideally I'd be able to tag a new release as being recommended for new users while telling maintainers that they don't need to bother updating the package.

IIRC there was also one bug fix since the 1.0.0 release (#15), so IMHO a new release would be nice.

I actually would be happy if a new release happens rather soon, because [the freeze for Debian's next stable release is near](https://release.debian.org/bullseye/freeze_policy.html). Back then I packaged commit e4cf9969 as `0.0.20171105+1+ge4cf9969-1` in Debian and by chance it retroactively has been declared to be `1.0.0`. So I never bothered to upload the package with a version number 1.0.0. Having an 1.0.1 to package, would make this look much better, because you really have to check git commit IDs to check that this actually _is_ the 1.0.0 release. But that's just a nice side effect of a release.

>  Is there some way (in the Debian world) for upstream to communicate this?

Changelog or release notes, I'd say.

**Comment by derat** [comment]
Sorry for the ambiguity. My question was about the release, and you answered it -- thanks!

I've tagged 40a2419829a05ad37f63fa4797ba8d4c9cbc6557 as [v1.0.1](https://github.com/derat/xsettingsd/releases/tag/v1.0.1).

**Comment by eszlari** [comment]
Unfortunately, you didn't update the version in CMakeLists.txt.

**Comment by derat** [comment]
Sigh. Okay, v1.0.2 it is.

**Comment by xtaran** [comment]
Thanks, also for the 1.0.2. ;-)

**Comment by xtaran** [comment]
I finally managed to upload `1.0.2-1` last night to Debian Unstable, too.
