### ISSUE TITLE
Load settings from different config file

### ISSUE THREAD

**Issue by adi1090x** [derat/xsettingsd#24]
So, i was thinking if it is possible to load settings from a different file (let's say ~/.config/xsettingsd) rather than ~/.xsettingsd

(So we can have different look and feel in each window manager)

Something like : `xsettingsd --config ~/.config/xsettingsd`

**Comment by derat** [comment]
It's been forever since I've looked at this code, but I believe that there's already a `--config` (or `-c`) flag for specifying an alternate configuration file. See https://github.com/derat/xsettingsd/blob/master/xsettingsd.cc#L41 (or run `xsettingsd --help`) for a list of all flags, and feel free to let me know if it doesn't work.

**Comment by adi1090x** [comment]
That is correct, the -c or --config flag already exists, don't know why I've not checked it first.

Thank you!
